#ifndef MAIN_SIMPLE_LUA_H
#define MAIN_SIMPLE_LUA_H

// Simplified embedded Lua script for SD card + LVGL demo
static const char* main_simple_lua_script = 
"print('=== ESP32-S3 LuaRTOS Demo ===')\n"
"\n"
"-- Test SD card if available\n"
"if sdcard then\n"
"    print('SD card module available')\n"
"    local init_ok, init_err = sdcard.init()\n"
"    if init_ok then\n"
"        print('SD card initialized')\n"
"        local mount_ok, mount_err = sdcard.mount()\n"
"        if mount_ok then\n"
"            print('SD card mounted successfully')\n"
"            local test_data = 'Hello from ESP32-S3!\\n' .. os.date()\n"
"            local write_ok, write_size = sdcard.write_file('test.txt', test_data)\n"
"            if write_ok then\n"
"                print('Created test file: ' .. write_size .. ' bytes')\n"
"            end\n"
"        else\n"
"            print('SD card mount failed: ' .. (mount_err or 'unknown'))\n"
"        end\n"
"    else\n"
"        print('SD card init failed: ' .. (init_err or 'unknown'))\n"
"    end\n"
"else\n"
"    print('SD card module not available')\n"
"end\n"
"\n"
"-- Create simple LVGL interface\n"
"print('Creating LVGL interface...')\n"
"local scr = lvgl.scr_act()\n"
"lvgl.obj_set_style_bg_color(scr, 0x001122, lvgl.PART_MAIN())\n"
"\n"
"-- Main title\n"
"local title = lvgl.label_create(scr)\n"
"lvgl.label_set_text(title, 'ESP32-S3 LuaRTOS')\n"
"lvgl.obj_set_style_text_color(title, lvgl.color_white(), lvgl.PART_MAIN())\n"
"lvgl.obj_align(title, lvgl.ALIGN_TOP_MID(), 0, 10)\n"
"\n"
"-- Status info\n"
"local status = lvgl.label_create(scr)\n"
"local status_text = 'Lua: Ready\\nLVGL: Active'\n"
"if sdcard and sdcard.is_mounted() then\n"
"    status_text = status_text .. '\\nSD Card: Mounted'\n"
"else\n"
"    status_text = status_text .. '\\nSD Card: N/A'\n"
"end\n"
"lvgl.label_set_text(status, status_text)\n"
"lvgl.obj_set_style_text_color(status, 0xaaaaaa, lvgl.PART_MAIN())\n"
"lvgl.obj_align(status, lvgl.ALIGN_CENTER(), 0, -20)\n"
"\n"
"-- Demo button\n"
"local btn = lvgl.btn_create(scr)\n"
"lvgl.obj_set_size(btn, 120, 40)\n"
"lvgl.obj_align(btn, lvgl.ALIGN_CENTER(), 0, 30)\n"
"local btn_label = lvgl.label_create(btn)\n"
"lvgl.label_set_text(btn_label, 'Demo')\n"
"lvgl.obj_center(btn_label)\n"
"\n"
"-- Footer\n"
"local footer = lvgl.label_create(scr)\n"
"lvgl.label_set_text(footer, 'ESP32-S3 • ' .. os.date('%H:%M'))\n"
"lvgl.obj_set_style_text_color(footer, 0x666666, lvgl.PART_MAIN())\n"
"lvgl.obj_align(footer, lvgl.ALIGN_BOTTOM_MID(), 0, -10)\n"
"\n"
"-- Force refresh\n"
"lvgl.obj_invalidate(scr)\n"
"print('Demo ready!')\n";

#endif // MAIN_SIMPLE_LUA_H
